/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NT747 (https://sketchfab.com/ntdw)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/poe-dameron-x-wing-a7fd082a1ad54c32bacee493ddbc56df
title: Poe Dameron X wing
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useScroll } from '../helpers/ScrollControls'

export default function Model({ ...props }) {
  const scroll = useScroll()
  useFrame((state,delta) => {
    const offset = scroll.offset
    group.current.rotation.z += 0.001
    group.current.position.set(-Math.sin(offset)*(20/Math.sin(1)) + 6, 0, Math.sin(offset)*(5/Math.sin(1))-3)
  })
  const group = useRef()
  const { nodes, materials } = useGLTF('/xwing.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.default_initialShadingGroup_0.geometry} material={materials.initialShadingGroup} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/xwing.gltf')
